import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import PrimaryCard from '../components/PrimaryCard'

export default function Home( { articles } ) {
  console.log(articles)
  return (
    <div className={styles.container}>
      <Head>
        <title>NXT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>

        <h1>Welcome</h1>

        {articles.map ((article)=>{
          return (<div>
                  
                  <PrimaryCard
                  cardImageLocation={'/honda_side_profjpg.jpg'} 
                  cardHeader={article.title}
                  cardMeta={article.id}
                  cardDescription={article.body}

                  />
                  </div>)
        })}
      </div>


    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`)
  const articles = await res.json()
  
  return {
    props: {
      articles
    }
  } 
}
